name: 'PR Auto Assign'
on: [pull_request]

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-files@v1.1.1
      with: 
        config: '.github/assign-by-files.yml'
        token: ${{ secrets.GITHUB_TOKEN }}